
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "sentient",
    "password": "ilikevaporeon"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "sentient",
    "password": "ilikevaporeon"
}

###

GET http://localhost:3000/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlbnRpZW50IiwicGFzc3dvcmQiOiIkMmIkMTAkL25EeHZrUVBHZWdqVm4yRXVHZC80ZW80eS9PTFY1SFRSODc4L2IzZUd2Z2hEbUg5ZTg5VU8iLCJpYXQiOjE3MDU1OTcxOTksImV4cCI6MTcwNTU5NzI1OX0.6Pj4dcYDSTBii95A3o0MfwxYHb0C2pu1BwFlBJHDz3M

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlbnRpZW50IiwicGFzc3dvcmQiOiIkMmIkMTAkL25EeHZrUVBHZWdqVm4yRXVHZC80ZW80eS9PTFY1SFRSODc4L2IzZUd2Z2hEbUg5ZTg5VU8iLCJpYXQiOjE3MDU1OTcxOTl9.gBppAsonch2ajW6uJ8LektD9WRq8wJANTjduwkphIwo"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlbnRpZW50IiwicGFzc3dvcmQiOiIkMmIkMTAkL25EeHZrUVBHZWdqVm4yRXVHZC80ZW80eS9PTFY1SFRSODc4L2IzZUd2Z2hEbUg5ZTg5VU8iLCJpYXQiOjE3MDU1OTcxMTl9.bw2RNfffevFHTSWcuoxT5hFma4rxXHAlwpiBLo5JDBQ"
}